version: '3.6'

# Services
services:

  # Nginx Service
  nginx:
    image: nginx:1.17-alpine
    ports:
      - 80:80
    volumes:
      - /www:/var/www/php:ro
      - ~/.docker/websrv/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - php

  # PHP Service
  php:
    build: ~/.docker/websrv/php
    working_dir: /var/www/php
    volumes:
      - /www:/var/www/php
    depends_on:
      - mysql

  # PhpMyAdmin Service
  phpmyadmin:
    image: jackgruber/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

  # MySQL Service
  mysql:
    image: yobasystems/alpine-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      # SCL2^x9&422@azY%Q*g5GBbN
      MYSQL_DATABASE: demo
    volumes:
      - ~/.docker/websrv/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - mysqldata:/var/lib/mysql

# Volumes
volumes:

  mysqldata:
